### PR TITLE
Is it possible to add this line, it makes it work for me on win8x64 / no...

### PR DESCRIPTION
**Pull request by refack**
...de0.10.20x64

### CODE REVIEW

**Comment by cowboy** [comment]
I need a list of operating systems and shells to test PRs on for this plugin, because every change needs to be tested in every version of Windows and shell.

But at the very least, every permutation of:
- Windows 7
- Windows 8

And:
- cmd.exe
- PowerShell
- git-bash

Should suffice.

**Comment by Bartvds** [comment]
@cowboy Do you have machines or VM's to test on? 

If not, are you aware of these? http://www.modern.ie/en-us/virtualization-tools

Also if you like [Vagrant](http://vagrantup.com/) then there is also [this project](https://github.com/WinRb/vagrant-windows) that might help you automate things for windows.

If you have a setup already I'm very interested to hear what system it uses (for my own work :)

**Comment by cowboy** [comment]
I only have a single Windows 7 x64 machine with the listed shells. I've been relying on others like @vladikoff and @shama to help test. I have a few VMs, but I've noticed issues with `fs.notify` in them, so I try to avoid using them for testing when possible.

**Comment by refack** [comment]
I tested it on all premutations of [Windows 7/8] x [cmd, bash, [WebStorm](http://www.jetbrains.com/webstorm/) (pipes to Java)]

**Comment by Bartvds** [comment]
@cowboy that is very good to know, thanks.

I still use a Vista 64 workstation so I can run tests.

For now I ran @refack's tests, also in cmd.exe and git bash, but I'm afraid some fail randomly:

I used https://github.com/refack/node-exit/tree/patch-1 (https://github.com/refack/node-exit/commit/3e8673434d896876cf5aaf9e73852ce0797e3a96)

Here are dumps of 4 results (2x cmd.exe, 2x git bash): https://gist.github.com/Bartvds/6965324

Notice how the failing tests are inconsistent between runs (I tried it few times more and it keeps changing slightly)

I also ran the tests from before this edit multiple times and they keep passing.

Let me know if I can do something to help.

**Comment by Bartvds** [comment]
I realized I forgot to check my node version: this was on node v0.10.17: but the update to v0.10.20 also fails in same way.

**Comment by refack** [comment]
Crazy...
I'll see what I can do.

**Comment by cowboy** [comment]
@Bartvds do the tests fail with the current released version?

**Comment by Bartvds** [comment]
I tested the one on your repo tagged v0.1.1 multiple times, it never failed

Also in my project I use [this commit](https://github.com/gruntjs/grunt/commit/0a4e6e38867cde1c396eb99820436027dccf8023) as grunt git-url dependency, it uses exit 0.1.1 and it works as expected (even with some funky grunt sub-process stuff).

**Comment by cowboy** [comment]
Based on @Bartvds's previous comment, it seems like this PR is failing randomly, whereas v0.1.1 isn't. I definitely can't merge this PR in if the fix is **more** broken than the current release.

I'm going to close this issue for now, please re-open it if you can show that it works reliably. At that point, I'll be looking for others to validate those results.

**Comment by vladikoff** [comment]
This didn't work for me in `cmd.exe` on Win7

**Pull request closed without merging**
